# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[25,)"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/williambl/EssentialFeatures/issues"



# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]

# The modid of the mod
modId="essentialfeatures"

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${version}"

 # A display name for the mod
displayName="Essential Features"

# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="https://raw.githubusercontent.com/williambl/EssentialFeatures/master/update.json"

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="http://williambl.com/essentialfeatures"

# A file name (in the root of the mod JAR) containing a logo for display
logoFile=""

# A text field displayed in the mod UI
credits="/u/Jake_Jeremy made the smooth glowstone texture. /u/DiamondHammer made the polished glowstone texture. github.com/Palmidence made the ocean music, scarlet music and texture, lo-fi music, the powered viewed block texture and the cereal texture."

# A text field displayed in the mod UI
authors="Willbl3pic"

# The description text for the mod (multi line!)
description='''
This is a long form description of the mod. You can write whatever you want here
'''



# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.essentialfeatures]]
    # the modid of the dependency
    modId="forge"
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true
    # The version range of the dependency
    versionRange="[25,)"
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.essentialfeatures]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"